In [4]:
data = r"3993249.csv"

In [5]:
import pandas as pd
import torch
import numpy as np

def create_tensors(using_stations):
    df = pd.read_csv(data)
    df = df[['STATION', 'DATE', 'PRCP']]
    df = df.pivot(index='DATE', columns='STATION', values='PRCP')
    df = df[using_stations]
    df = df.loc['1938-04-01':]
    df = df.ffill()

    daily = []
    observations = []

    for idx, row in df.iterrows():
        date = pd.to_datetime(row.name)
        obs  = torch.tensor(row.values)

        d = date.day_of_year
        dt = torch.tensor([d / 365.25, np.sin(2 * np.pi * d / 365.25), np.cos(2 * np.pi * d / 365.25)])

        daily.append(dt)
        observations.append(obs)

    without_days = torch.stack(observations, dim=0)
    print(without_days)

    days = torch.stack(daily, dim=0)
    print(days)

    # tensor of daily observations plus day of year info
    with_days = torch.cat((without_days, days), dim=1)
    print(with_days)

    stations_str = '-'.join(x for x in using_stations)
    torch.save(with_days, f'data-{stations_str}.bin')

In [ ]:
create_tensors(['USC00251825', 'USC00254335', 'USC00255810'])
create_tensors(['USC00254335', 'USC00255810', 'USW00014935'])
create_tensors(['USC00251825', 'USC00254335', 'USC00255810', 'USW00014935'])


In [6]:
create_tensors(['USC00251825'])
create_tensors(['USC00254335'])
create_tensors(['USC00255810'])
create_tensors(['USW00014935'])

tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=torch.float64)
tensor([[ 0.2491,  1.0000,  0.0054],
        [ 0.2519,  0.9999, -0.0118],
        [ 0.2546,  0.9996, -0.0290],
        ...,
        [ 0.2765,  0.9861, -0.1659],
        [ 0.2793,  0.9831, -0.1828],
        [ 0.2820,  0.9799, -0.1997]], dtype=torch.float64)
tensor([[ 0.0000,  0.2491,  1.0000,  0.0054],
        [ 0.0000,  0.2519,  0.9999, -0.0118],
        [ 0.0000,  0.2546,  0.9996, -0.0290],
        ...,
        [ 0.0000,  0.2765,  0.9861, -0.1659],
        [ 0.0000,  0.2793,  0.9831, -0.1828],
        [ 0.0000,  0.2820,  0.9799, -0.1997]], dtype=torch.float64)
tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=torch.float64)
tensor([[ 0.2491,  1.0000,  0.0054],
        [ 0.2519,  0.9999, -0.0118],
        [ 0.2546,  0.9996, -0.0290],
        ...,
        [ 0.2765,  0.9861, -0.1659],
        [ 0.2793,  0.9831, -0.182

In [ ]:
import pandas as pd

df = pd.read_csv(data)
df = df[['STATION', 'DATE', 'PRCP']]
df = df.pivot(index='DATE', columns='STATION', values='PRCP')
df = df[['USC00251825', 'USC00254335', 'USC00255810', 'USW00014935']]
df = df.loc['1938-04-01':]
df = df.ffill()

In [ ]:
import torch
import numpy as np

daily = []
observations = []

for idx, row in df.iterrows():
    date = pd.to_datetime(row.name)
    obs  = torch.tensor(row.values)

    d = date.day_of_year
    dt = torch.tensor([d / 365.25, np.sin(2 * np.pi * d / 365.25), np.cos(2 * np.pi * d / 365.25)])

    daily.append(dt)
    observations.append(obs)

In [ ]:
# tensor of daily observations with no day of year data attached
without_days = torch.stack(observations, dim=0)
print(without_days)

days = torch.stack(daily, dim=0)
print(days)

# tensor of daily observations plus day of year info
with_days = torch.cat((without_days, days), dim=1)
print(with_days)